import { chromium } from 'playwright';
const S='/private/tmp/claude-501/-Users-alex/7b318732-29a6-4a8e-b2aa-2cabee36b183/scratchpad/kzby/';
const b = await chromium.launch({channel:'chrome'});
const ctx = await b.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});
const p = await ctx.newPage();
await p.goto('http://localhost:8102/bbq.html', {waitUntil:'networkidle'});
await p.locator('[data-burger]').click(); await p.waitForTimeout(400);
await p.screenshot({path:S+'by_m_burger.png'});
console.log((await p.locator('[data-nav]').innerText()).replace(/\n+/g,' | '));
await b.close();
